development:
  adapter: mysql2
  encoding: utf8
  database: nhc_development
  username: root
  password: bandana
  host: localhost
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: nhc_test
  username: root
  password: bandana
  host: localhost
  port: 3306

production:
  host: ec2-54-225-134-223.compute-1.amazonaws.com
  adapter: postgresql
  encoding: unicode
  database: d5nk18ugmqs66s
  pool: 5
  username: hazlchyjdkpnem
  password: u85yxy8Y0V12C0WlwPaQQBqrU4
  port: 5432
